import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import Hero from '../components/Hero'
import HomeSection from '../components/HomeSection'
import Testimonials from '../components/Testimonials'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero
        heading={'The Commune Review'}
        message={"Welcome to The Commune, a community of people who like to go out and have fun while earning rewards."}
        bg_image={'back-img'}
      />
      <About />
      <HomeSection
        id={"restaurants"}
        title={"Restaurants"}
        img={"restaurants-bg"}
        fileID={'hamburger'}>
        Earn tokens everytime you visit a restaurant.
      </HomeSection>
      <HomeSection
        id={"events"}
        title={"Events"}
        img={"events-bg"}
        fileID={'hamburger'}>
        Earn tokens everytime you attend an event.
      </HomeSection>
      <Testimonials />
      <Contact />
      
      <Footer />
    </div>
  )
}
