import Head from 'next/head'
import Hero from '../components/Hero'
import RestaurantsHomeSection from '../components/RestaurantsHomeSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero
        heading={'The Commune Review'}
        message={"We've made it easy for you to earn rewards by posting your reviews and thoughts on places you go to. A platform for people to share their experiences and earn rewards for doing so. Businesses also learn about your likes and dislikes and improve your overall experience"}
      />
      <RestaurantsHomeSection
        id={"restaurants"}
        title={"Restaurants"}
        img={"restaurants-bg"}
        fileID={'hamburger'}>
        Earn tokens everytime you visit a restaurant.
      </RestaurantsHomeSection>
      <RestaurantsHomeSection
        id={"events"}
        title={"Events"}
        img={"events-bg"}
        fileID={'hamburger'}>
        Earn tokens everytime you attend an event.
      </RestaurantsHomeSection>
    </div>
  )
}
