import Head from 'next/head'
import Hero from '../components/Hero'
import RestaurantsHomeSection from '../components/RestaurantsHomeSection'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero heading={'The Commune Review'} message={"Welcome to The Commune, a place where we have gamified outgoing"} />
      <RestaurantsHomeSection />
    </div>
  )
}
